### ISSUE TITLE
Can you add new version exo player 2.11.7?

### ISSUE THREAD

**Issue by Kronos0041** [flipkart-incubator/madman-android#17]
I'm trying update Exo player in demo from version 2.10.3 to 2.11.7 and getting an exception

`java.lang.NoSuchMethodError: No virtual method getAdGroupIndexForPositionUs(J)I in class Lcom/google/android/exoplayer2/source/ads/AdPlaybackState; or its super classes (declaration of 'com.google.android.exoplayer2.source.ads.AdPlaybackState' appears in /data/app/com.liqvid.liqvid_ima_test-1/base.apk)
        at com.flipkart.madman.exo.extension.MadmanAdLoader.startAdPlayback(MadmanAdLoader.kt:722)
        at com.flipkart.madman.exo.extension.MadmanAdLoader.onAdManagerLoaded(MadmanAdLoader.kt:389)
        at com.flipkart.madman.Madman$loadRequest$1.invoke(Madman.kt:152)
        at com.flipkart.madman.Madman$loadRequest$1.invoke(Madman.kt:64)
        at com.flipkart.madman.loader.impl.BaseAdLoader$parseResponse$1.onSuccess(BaseAdLoader.kt:55)
        at com.flipkart.madman.loader.impl.BaseAdLoader$parseResponse$1.onSuccess(BaseAdLoader.kt:40)
        at com.flipkart.madman.parser.XmlParser$parse$1$1.run(XmlParser.kt:78)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5294)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)`

**Comment by anirudhramanan** [comment]
Madman currently supports `2.9.6` version of exo-player. I'm working on migrating it to the new version of exo, will update this thread once done.
